### PR TITLE
Error email improvements

### PR DESCRIPTION
**Pull request by marcinapostoluk**
- Separating out error email so that it can be specified independently via UI. This is so that successful reports can be sent to target audience while errors to notebook maintainer
- If no error email is specified errors won't be sent to the regular email any more. The assumption here is that notebook maintainer will monitor it manually. This is a change of behavior as after an upgrade to the new version emails will no longer be sent on failure unless changes the config explicitly. If strong objections I can default it to use regular email although this  disallows configuring a case where we do want regular emails sent but not the error emails.
- Storing regular and error emails together in each notebook result - in case one wants to re-run we need to have them both as the result of the re-run can be either a success or a failure

### CODE REVIEW

**Comment by jonbannister** [comment]
> If no error email is specified errors won't be sent to the regular email any more. The assumption here is that notebook maintainer will monitor it manually. 

I don't think this is a safe assumption. Plenty of internal users only notice that their scheduled report is failing when they get the email (many don't check the webapp at all).

**Comment by marcinapostoluk** [comment]
> > If no error email is specified errors won't be sent to the regular email any more. The assumption here is that notebook maintainer will monitor it manually.
> 
> I don't think this is a safe assumption. Plenty of internal users only notice that their scheduled report is failing when they get the email (many don't check the webapp at all).

Sure, no problem, changed to default to regular email now if error email not specified

**Comment by jonbannister** [comment]
- [ ] Please add to the CHANGELOG

**Review by jonbannister — APPROVED** [review]
LGTM

**Pull request merged**
